httplug:
    plugins:
        retry:
            retry: 1

    discovery:
        client: 'auto'

    clients:
        app:
            factory: 'httplug.factory.guzzle6'
            http_methods_client: true
            plugins:
                - 'httplug.plugin.content_length'
                - 'httplug.plugin.redirect'
